name: log_my_ride
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  floor: ^1.5.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  faker: ^2.1.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.1

  faker_dart: ^0.2.2
  random_avatar: ^0.0.8
  multiavatar: ^0.1.5
  line_icons: ^2.0.3
  syncfusion_flutter_charts: ^20.2.0
  syncfusion_flutter_gauges: ^20.4.54
  syncfusion_flutter_calendar: ^20.4.54
  audioplayers: ^6.1.0
  flutter_local_notifications: ^17.2.2
  flutter_osm_plugin: ^1.2.0
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  fl_chart: ^0.69.0
  animate_do: ^3.3.4
  flutter_markdown: ^0.7.3+1
  timelines: ^0.1.0
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  image_picker: ^1.1.2
  easy_stepper: ^0.8.5+1
  smooth_page_indicator: ^1.2.0+3
  timeline_tile: ^2.0.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
    - assets/animations/
