// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_uxIU-eH4NUN6Rqjl81Z1_FrT0dGedc',
    appId: '1:660154104955:web:d84ee86e8f910c6511f6de',
    messagingSenderId: '660154104955',
    projectId: 'log-my-ride-1012b',
    authDomain: 'log-my-ride-1012b.firebaseapp.com',
    storageBucket: 'log-my-ride-1012b.appspot.com',
    measurementId: 'G-WZR124GMNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdNQMKoNSlSSCGnAzeSRFdBLlV5ziZiQ',
    appId: '1:660154104955:android:d9729a9daafedb8511f6de',
    messagingSenderId: '660154104955',
    projectId: 'log-my-ride-1012b',
    storageBucket: 'log-my-ride-1012b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAEU0P44OGpWwr0AG6hxPD5s9IDWYHNsM',
    appId: '1:660154104955:ios:6c4c1409be15eb6411f6de',
    messagingSenderId: '660154104955',
    projectId: 'log-my-ride-1012b',
    storageBucket: 'log-my-ride-1012b.appspot.com',
    iosBundleId: 'com.logmyride.logMyRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAEU0P44OGpWwr0AG6hxPD5s9IDWYHNsM',
    appId: '1:660154104955:ios:6c4c1409be15eb6411f6de',
    messagingSenderId: '660154104955',
    projectId: 'log-my-ride-1012b',
    storageBucket: 'log-my-ride-1012b.appspot.com',
    iosBundleId: 'com.logmyride.logMyRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_uxIU-eH4NUN6Rqjl81Z1_FrT0dGedc',
    appId: '1:660154104955:web:835f8326313bb6b411f6de',
    messagingSenderId: '660154104955',
    projectId: 'log-my-ride-1012b',
    authDomain: 'log-my-ride-1012b.firebaseapp.com',
    storageBucket: 'log-my-ride-1012b.appspot.com',
    measurementId: 'G-R3Q67ZM9G6',
  );
}
